name: Playwright Tests Test
on:
  push:
    branches: [ main, master, test, prod ]
  pull_request:
    branches: [ main, master, test, prod ]
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"
